### ISSUE TITLE
Activity Rewarded disable another plugin LibertyBans for "boolean org.bukkit.Server.isGlobalTickThread()"

### ISSUE THREAD

**Issue by ItsRealPerson** [CoolDCB/ActivityRewarder#4]
Hi, after update ActivityRewarded to recoded version and restart my server i receive that message from console when the plugin is enable

`java.lang.NoSuchMethodError: 'boolean org.bukkit.Server.isGlobalTickThread()'
        at space.arim.morepaperlib.scheduling.GracefulScheduling.isOnGlobalRegionThread(GracefulScheduling.java:146) ~[ActivityRewarder-2.0.2.jar:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFutureImpl.isPrimaryThread0(BukkitFactoryOfTheFutureImpl.java:59) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.concurrent.MainThreadCachingFutureFactory.isPrimaryThread(MainThreadCachingFutureFactory.java:49) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFutureImpl.create(BukkitFactoryOfTheFutureImpl.java:53) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFuture.create(BukkitFactoryOfTheFuture.java:56) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitFactoryOfTheFuture.create(BukkitFactoryOfTheFuture.java:45) ~[LibertyBans-ClassLoader:?]
        at space.arim.api.env.bukkit.BukkitPlatformHandleImpl.createFuturesFactory(BukkitPlatformHandle.java:64) ~[LibertyBans-ClassLoader:?]
        at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
        at space.arim.libertybans.core.service.StandardAsynchronicityManager.startup(StandardAsynchronicityManager.java:90) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.LifecycleGodfather.startup0(LifecycleGodfather.java:75) ~[LibertyBans-ClassLoader:?]
        at space.arim.libertybans.core.AbstractBaseFoundation.timedEvent(AbstractBaseFoundation.java:126) ~[LibertyBans-ClassLoader:?]
[09:36:33 INFO]: [LibertyBans] Disabling LibertyBans v1.1.0-RC1`

And if disable ActivityRewarder LibertyBans work without a problem

ScreenShot with Activity Rewarded and LibertyBans
![image](https://github.com/CoolDCB/ActivityRewarder/assets/85977281/7a7b07cd-c8f2-4d5b-b79e-b4eeab300e51)
![image](https://github.com/CoolDCB/ActivityRewarder/assets/85977281/176e2926-de98-4c1f-b8c1-b553ddd2bd80)
![image](https://github.com/CoolDCB/ActivityRewarder/assets/85977281/642fee4e-b014-4338-aeba-2af9a9597b5a)

ScreenShot without ActivityRewarder
![image](https://github.com/CoolDCB/ActivityRewarder/assets/85977281/3ce5cee8-8478-4114-b285-1cc8585ec3ae)
![image](https://github.com/CoolDCB/ActivityRewarder/assets/85977281/3d11d054-834e-4069-9e38-c02f4c4da68c)

Thank you and have a nice day

**Comment by CoolDCB** [comment]
Thanks for letting me know about this! I'll have a look into this!

**Comment by CoolDCB** [comment]
This should now be resolved in [3d8f042](https://github.com/CoolDCB/ActivityRewarder/commit/3d8f042779c73b952bae13ac8d5f12f45de11bc7). Will push the update to spigot in a moment
