### ISSUE TITLE
[Error] Upgrade version 2.0.4 to 2.1.4 and then occur error when issue command /rewards

### ISSUE THREAD

**Issue by abumpkin** [CoolDCB/ActivityRewarder#7]
## Logs

```txt
[11:38:22] [Server thread/INFO]: test3 issued server command: /rewards
[11:38:22] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rewards' in plugin ActivityRewarder v2.1.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1001) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.1.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2447) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$22(ServerGamePacketListenerImpl.java:2407) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1365) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1342) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1335) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1313) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "b64" is null
	at me.dave.activityrewarder.utils.skullcreator.NewSkullCreator.makeProfile(NewSkullCreator.java:60) ~[ActivityRewarder-2.1.4.jar:?]
	at me.dave.activityrewarder.utils.skullcreator.NewSkullCreator.mutateItemMeta(NewSkullCreator.java:35) ~[ActivityRewarder-2.1.4.jar:?]
	at me.dave.activityrewarder.utils.SimpleItemStack.getItemStack(SimpleItemStack.java:169) ~[ActivityRewarder-2.1.4.jar:?]
	at me.dave.activityrewarder.module.dailyrewards.DailyRewardsGui.lambda$recalculateContents$5(DailyRewardsGui.java:274) ~[ActivityRewarder-2.1.4.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at me.dave.activityrewarder.module.dailyrewards.DailyRewardsGui.recalculateContents(DailyRewardsGui.java:265) ~[ActivityRewarder-2.1.4.jar:?]
	at me.dave.activityrewarder.gui.abstracts.AbstractGui.openInventory(AbstractGui.java:86) ~[ActivityRewarder-2.1.4.jar:?]
	at me.dave.activityrewarder.commands.RewardCmd.onCommand(RewardCmd.java:397) ~[ActivityRewarder-2.1.4.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

## `config.yml`

```yml
# For more details on configuring ActivityRewarder check out the documentation at https://dave-12.gitbook.io/activity-rewarder

# Enable or disable specific ActivityRewarder modules
modules:
  daily-rewards: true
  daily-playtime-goals: true
  global-playtime-goals: false

# The length in seconds between reminders being sent (Set to -1 to disable)
reminder-period: 600
# The sound that will be played when a player is sent a reminder
reminder-sound: block_note_block_pling

# Display items for different reward categories
categories:
  small:
    material: player_head
    skull-texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTAxYzYzYzIwM2ExODQxZGUyN2EwZTA5YTI5NWY1Yjg3MzM2MjcwMjRmMTY2OGEwMWQyMDE4NmEzZjg2MzA0MCJ9fX0=
  medium:
    material: player_head
    skull-texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjEwMzhjZGM4NDIzNGI1YWZiM2FlYTg1M2JmM2QwNTE3NWQxOWFlN2I0ODc1YTkxYjUyZjc2NmMwN2IzZGIwYiJ9fX0=
  large:
    material: player_head
    skull-texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjUyODdhZjk3ZjkzZDM3MTg5NzNmNGUxM2VkMGZhM2E2ZjQzOWU3MmMxNDVmZTRjZDkwMmIwNWMxYzEwYWYxOCJ9fX0=

# Display item templates
item-templates:
  # Template for default rewards
  default-reward:
    display-name: "&#A5B8FEDay %day%"
  # Template for collectable rewards
  redeemable-reward:
    material: player_head
    skull-texture: e3RleHR1cmVzOntTS0lOOnt1cmw6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmI1N2Y0ODVlOWVjY2E1MzIzNDQ4NTBjNTFhYjQ0ZGQ2YWE1ZDQ1MTRiMzFjNmRmOWZjMjBlMzZiM2E4OWQ4YyJ9fX0=
    display-name: "&#f5e389Day %day% - Redeemable"
    enchanted: true
  # Template for collected rewards
  collected-reward:
    material: player_head
    skull-texture: e3RleHR1cmVzOntTS0lOOnt1cmw6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWZkNTEyY2NlNGU3OTUyOGI2MGIzNWRmZTZmN2JmYzg0M2IyOTY4NDIxMDViMWNkMjY4MjdiNTkwOGIxMzU0ZCJ9fX0=
    display-name: "&#f5e389Day %day% - Collected"
    enchanted: false
  # Template for missed rewards
  missed-reward:
    material: player_head
    skull-texture: e3RleHR1cmVzOntTS0lOOnt1cmw6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGRkMzBhYWMyYTFmMmQxOGM3NzU1Y2ZjYTJiYzYwOWZjMzkxZjQxOTg5YjA2NmNlOTMxNjA3NzY5MDZiZTg1YSJ9fX0=
    display-name: "&7Day %day% &8(Missed)"
  # Template for upcoming reward
  upcoming-reward:
    lore:
      - "&7&o- Upcoming reward"

  # Template for border items - more items can be created like this to be used within the gui templates
  '#':
    material: light_blue_stained_glass_pane
    display-name: "&7"
  'P':
    material: player_head
    display-name: "&#A5B8FE&lPlayer Info:"
    skull-texture: mirror
    lore:
      # - "&#c4f8ffDays: &f%rewarder_day_num%"
      - "&#c4f8ffCount Down: &f%rewarder_countdown%"
      - "&#c4f8ffStreak: &f%rewarder_streak%"
      - "&#c4f8ffHighest Streak: &f%rewarder_highest_streak%"

messages:
  prefix: "<gradient:#CEB5FE:#81BAFE><bold>Rewards</bold></gradient> &8» "
  reload: "&#b7faa2ActivityRewarder has been reloaded &#66b04f🔃"
  reminder: "%prefix% &#ffe27aIt looks like you haven't collected today's reward from &#ffc940/rewards"
  daily-reward-given: "&#b7faa2You have collected today's daily reward"
  daily-playtime-reward-given: "&#b7faa2You have collected your rewards for playing &#66b04f%minutes% &#b7faa2minutes"
  global-playtime-reward-given: "&#b7faa2You have collected your rewards for playing &#66b04f%minutes% &#b7faa2minutes"
  reset: "&#ffe27aAre you sure you want to reset &#e0c01b%target%'s &#ffe27adays? Type &#e0c01b'/rewards reset %target% confirm' &#ffe27ato confirm"
  reset-days: "&#ffe27aAre you sure you want to reset &#e0c01b%target%'s &#ffe27adays? Type &#e0c01b'/rewards reset-days %target% confirm' &#ffe27ato confirm"
  set-days: "&#ffe27aAre you sure you want to set &#e0c01b%target%'s &#ffe27adays? Type &#e0c01b'/rewards set-days %target% %day% confirm' &#ffe27ato confirm"
  set-days-confirm: "&#66b04f%target%'s &#b7faa2day number has been set to &#66b04f%day%"
  reset-streak: "&#ffe27aAre you sure you want to reset &#e0c01b%target%'s &#ffe27astreak? Type &#e0c01b'/rewards reset-streak %target% confirm' &#ffe27ato confirm"
  set-streak: "&#ffe27aAre you sure you want to set &#e0c01b%target%'s &#ffe27astreak? Type &#e0c01b'/rewards set-streak %target% %streak% confirm' &#ffe27ato confirm"
  set-streak-confirm: "&#66b04f%target%'s &#b7faa2streak has been set to &#66b04f%streak%"
  unknown-player: "&#ff6969Could not find &#d13636%player%"
  no-permissions: "&#ff6969Insufficient permissions"
  incorrect-usage: "&#ff6969Incorrect usage try &#d13636%command-usage%"

# Performance mode only stores rewards that are currently viewable to players.
# The config will automatically reload at the start of each day when enabled
enable-performance-mode: false

# Debug Modes: none, daily, playtime, all
debug-mode: none
```

**Comment by CoolDCB** [comment]
My apologies for a delayed reply, for whatever reason GitHub did not notify me about this issue, the bug should be resolved in the following version:
[ActivityRewarder-2.1.5-BETA.zip](https://github.com/CoolDCB/ActivityRewarder/files/13113632/ActivityRewarder-2.1.5-BETA.zip)
