### ISSUE TITLE
error in use /rewards

### ISSUE THREAD

**Issue by BallkingCN** [CoolDCB/ActivityRewarder#9]
it happened in the lastest version(2.1.5 beta) for all players
and it also happened on some players(not everyon) in 2.1.4

<[01:45:00 INFO]: BallkingCN issued server command: /rewards
�[01:45:00 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rewards' in plugin ActivityRewarder v2.1.5-BETA
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1048) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[kaiiju-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2405) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$17(ServerGamePacketListenerImpl.java:2365) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1523) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 27 path $.textures.skin.url
        at com.google.gson.internal.Streams.parse(Streams.java:61) ~[gson-2.10.jar:?]
        at com.google.gson.JsonParser.parseReader(JsonParser.java:102) ~[gson-2.10.jar:?]
        at com.google.gson.JsonParser.parseReader(JsonParser.java:70) ~[gson-2.10.jar:?]
        at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[gson-2.10.jar:?]
        at me.dave.activityrewarder.utils.skullcreator.NewSkullCreator.getUrlFromBase64(NewSkullCreator.java:82) ~[ActivityRewarder-2.1.5-BETA.jar:?]
        at me.dave.activityrewarder.utils.skullcreator.NewSkullCreator.makeProfile(NewSkullCreator.java:71) ~[ActivityRewarder-2.1.5-BETA.jar:?]
        at me.dave.activityrewarder.utils.skullcreator.NewSkullCreator.mutateItemMeta(NewSkullCreator.java:34) ~[ActivityRewarder-2.1.5-BETA.jar:?]
        at me.dave.activityrewarder.utils.SimpleItemStack.getItemStack(SimpleItemStack.java:171) ~[ActivityRewarder-2.1.5-BETA.jar:?]
        at me.dave.activityrewarder.module.dailyrewards.DailyRewardsGui.lambda$recalculateContents$5(DailyRewardsGui.java:274) ~[ActivityRewarder-2.1.5-BETA.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at me.dave.activityrewarder.module.dailyrewards.DailyRewardsGui.recalculateContents(DailyRewardsGui.java:265) ~[ActivityRewarder-2.1.5-BETA.jar:?]
        at me.dave.activityrewarder.gui.abstracts.AbstractGui.openInventory(AbstractGui.java:86) ~[ActivityRewarder-2.1.5-BETA.jar:?]
        at me.dave.activityrewarder.commands.RewardCmd.onCommand(RewardCmd.java:400) ~[ActivityRewarder-2.1.5-BETA.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 14 more
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 27 path $.textures.skin.url
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:500) ~[gson-2.10.jar:?]
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:422) ~[gson-2.10.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:779) ~[gson-2.10.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar:?]
        at com.google.gson.internal.Streams.parse(Streams.java:49) ~[gson-2.10.jar:?]
        at com.google.gson.JsonParser.parseReader(JsonParser.java:102) ~[gson-2.10.jar:?]
        at com.google.gson.JsonParser.parseReader(JsonParser.java:70) ~[gson-2.10.jar:?]
        at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[gson-2.10.jar:?]
        at me.dave.activityrewarder.utils.skullcreator.NewSkullCreator.getUrlFromBase64(NewSkullCreator.java:82) ~[ActivityRewarder-2.1.5-BETA.jar:?]
        at me.dave.activityrewarder.utils.skullcreator.NewSkullCreator.makeProfile(NewSkullCreator.java:71) ~[ActivityRewarder-2.1.5-BETA.jar:?]
        at me.dave.activityrewarder.utils.skullcreator.NewSkullCreator.mutateItemMeta(NewSkullCreator.java:34) ~[ActivityRewarder-2.1.5-BETA.jar:?]
        at me.dave.activityrewarder.utils.SimpleItemStack.getItemStack(SimpleItemStack.java:171) ~[ActivityRewarder-2.1.5-BETA.jar:?]
        at me.dave.activityrewarder.module.dailyrewards.DailyRewardsGui.lambda$recalculateContents$5(DailyRewardsGui.java:274) ~[ActivityRewarder-2.1.5-BETA.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at me.dave.activityrewarder.module.dailyrewards.DailyRewardsGui.recalculateContents(DailyRewardsGui.java:265) ~[ActivityRewarder-2.1.5-BETA.jar:?]
        at me.dave.activityrewarder.gui.abstracts.AbstractGui.openInventory(AbstractGui.java:86) ~[ActivityRewarder-2.1.5-BETA.jar:?]
        at me.dave.activityrewarder.commands.RewardCmd.onCommand(RewardCmd.java:400) ~[ActivityRewarder-2.1.5-BETA.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 14 more

**Comment by CoolDCB** [comment]
Please can you send logs with https://smrt-1.com/paste it's very hard to read them just pasted in github

**Comment by BallkingCN** [comment]
> Please can you send logs with https://smrt-1.com/paste it's very hard to read them just pasted in github

https://smrt-1.com/pastes/GOOHTY9

**Comment by CoolDCB** [comment]
Please could you send me your config.yml

**Comment by BallkingCN** [comment]
[config.zip](https://github.com/CoolDCB/ActivityRewarder/files/13112861/config.zip)

**Comment by CoolDCB** [comment]
Are you sure this was happening on 2.1.4?

**Comment by BallkingCN** [comment]
> Are you sure this was happening on 2.1.4?

in 2.1.4 it is only happened on 2players,not all players

**Comment by CoolDCB** [comment]
This fixes a bug that started happening in one of the 2.1.5-BETA versions, if you get any instances going forward feel free to open a new issue :)

[ActivityRewarder-2.1.5-BETA.zip](https://github.com/CoolDCB/ActivityRewarder/files/13114013/ActivityRewarder-2.1.5-BETA.zip)

**Comment by BallkingCN** [comment]
> This fixes a bug that started happening in one of the 2.1.5-BETA versions, if you get any instances going forward feel free to open a new issue :)
> 
> [ActivityRewarder-2.1.5-BETA.zip](https://github.com/CoolDCB/ActivityRewarder/files/13114013/ActivityRewarder-2.1.5-BETA.zip)

ok!thanks for ur reply and helps for these days!

**Comment by CoolDCB** [comment]
No worries at all! Glad I can help
